import React from 'react';
import { Button } from 'react-bootstrap';
import differenceBy from "lodash/differenceBy";
import DataTableExtensions from 'react-data-table-component-extensions';
import DataTable from 'react-data-table-component';
import "react-data-table-component-extensions/dist/index.css";



const tableDataItems = [
    {
        id: '1',
        SNO: '1',
        FNAME: 'Bella',
        LNAME: 'Chloe',
        POSITION: 'System Developer',
        START: '2018/03/12',
        SALARY: '$654,765',
        MAIL: 'b.Chloe@datatables.net',
    },
    {
        id: '2',
        SNO: '2',
        FNAME: 'Donna',
        LNAME: 'Bond',
        POSITION: 'Account Manager',
        START: '2012/02/21',
        SALARY: '$543,654',
        MAIL: 'd.bond@datatables.net',
    },
    {
        id: '3',
        SNO: '3',
        FNAME: 'Harry',
        LNAME: 'Carr',
        POSITION: 'Technical Manager',
        START: '20011/02/87',
        SALARY: '$86,000',
        MAIL: 'h.carr@datatables.net',
    },
    {
        id: '4',
        SNO: '4',
        FNAME: 'Lucas',
        LNAME: 'Dyer',
        POSITION: 'Javascript Developer',
        START: '2014/08/23',
        SALARY: '$456,123',
        MAIL: 'l.dyer@datatables.net',
    },
    {
        id: '5',
        SNO: '5',
        FNAME: 'Karen',
        LNAME: 'Hill',
        POSITION: 'Sales Manager',
        START: '2010/7/14',
        SALARY: '$432,230',
        MAIL: 'k.hill@datatables.net',
    },
    {
        id: '6',
        SNO: '6',
        FNAME: 'Dominic',
        LNAME: 'Hudson',
        POSITION: 'Sales Assistant',
        START: '2015/10/16',
        SALARY: '$654,300',
        MAIL: 'd.hudson@datatables.net',
    },
    {
        id: '7',
        SNO: '7',
        FNAME: 'Herrod',
        LNAME: 'Chandler',
        POSITION: 'Integration Specialist',
        START: '2012/08/06',
        SALARY: '$137,500',
        MAIL: 'h.chandler@datatables.net',
    },
    {
        id: '8',
        SNO: '8',
        FNAME: 'Jonathan',
        LNAME: 'Ince',
        POSITION: 'junior Manager',
        START: '2012/11/23',
        SALARY: '$345,789',
        MAIL: 'j.ince@datatables.net',
    },
    {
        id: '9',
        SNO: '9',
        FNAME: "Leonard",
        LNAME: "Ellison",
        POSITION: "Junior Javascript Developer",
        START: "2010/03/19",
        SALARY: "$205,500",
        MAIL: "l.ellison@datatables.net",
    },
    {
        id: '10',
        SNO: '10',
        FNAME: "Madeleine",
        LNAME: "Lee",
        POSITION: "Software Developer",
        START: "20015/8/23",
        SALARY: "$456,890",
        MAIL: "m.lee@datatables.net",
    },
    {
        id: '11',
        SNO: '11',
        FNAME: "Karen",
        LNAME: "Miller",
        POSITION: "Office Director",
        START: "2012/9/25",
        SALARY: "$87,654",
        MAIL: "k.miller@datatables.net",
    },
    {
        id: '12',
        SNO: '12',
        FNAME: "Lisa",
        LNAME: "Smith",
        POSITION: "Support Lead",
        START: "2011/05/21",
        SALARY: "$342,000",
        MAIL: "l.simth@datatables.net",
    },
    {
        id: '13',
        SNO: '13',
        FNAME: "Morgan",
        LNAME: "Keith",
        POSITION: "Accountant",
        START: "2012/11/27",
        SALARY: "$675,245",
        MAIL: "m.keith@datatables.net",
    },
    {
        id: '14',
        SNO: '14',
        FNAME: "Nathan",
        LNAME: "Mills",
        POSITION: "Senior Marketing Designer",
        START: "2014/10/8",
        SALARY: "$765,980",
        MAIL: "n.mills@datatables.net",
    },
    {
        id: '15',
        SNO: '15',
        FNAME: "Ruth",
        LNAME: "May",
        POSITION: "office Manager",
        START: "2010/03/17",
        SALARY: "$654,765",
        MAIL: "r.may@datatables.net",
    },
    {
        id: '16',
        SNO: '16',
        FNAME: "Penelope",
        LNAME: "Ogden",
        POSITION: "Marketing Manager",
        START: "2013/5/22",
        SALARY: "$345,510",
        MAIL: "p.ogden@datatables.net",
    },
    {
        id: '17',
        SNO: '17',
        FNAME: "Sean",
        LNAME: "Piper",
        POSITION: "Financial Officer",
        START: "2014/06/11",
        SALARY: "$725,000",
        MAIL: "s.piper@datatables.net",
    },
    {
        id: '18',
        SNO: '18',
        FNAME: "Trevor",
        LNAME: "Ross",
        POSITION: "Systems Administrator",
        START: "2011/05/23",
        SALARY: "$237,500",
        MAIL: "t.ross@datatables.net",
    },
    {
        id: '19',
        SNO: '19',
        FNAME: "Vanessa",
        LNAME: "Robertson",
        POSITION: "Software Designer",
        START: "2014/6/23",
        SALARY: "$765,654",
        MAIL: "v.robertson@datatables.net",
    },
    {
        id: '20',
        SNO: '20',
        FNAME: "Una",
        LNAME: "Richard",
        POSITION: "Personnel Manager",
        START: "2014/5/22",
        SALARY: "$765,290",
        MAIL: "u.richard@datatables.net",
    },
    {
        id: '21',
        SNO: '21',
        FNAME: "Justin",
        LNAME: "Peters",
        POSITION: "Development lead",
        START: "2013/10/23",
        SALARY: "$765,654",
        MAIL: "j.peters@datatables.net",
    },
    {
        id: '22',
        SNO: '22',
        FNAME: "Adrian",
        LNAME: "Terry",
        POSITION: "Marketing Officer",
        START: "2013/04/21",
        SALARY: "$543,769",
        MAIL: "a.terry@datatables.net",
    },
    {
        id: '23',
        SNO: '23',
        FNAME: "Cameron",
        LNAME: "Watson",
        POSITION: "Sales Support",
        START: "2013/9/7",
        SALARY: "$675,876",
        MAIL: "c.watson@datatables.net",
    },
    {
        id: '24',
        SNO: '24',
        FNAME: "Evan",
        LNAME: "Terry",
        POSITION: "Sales Manager",
        START: "2013/10/26",
        SALARY: "$66,340",
        MAIL: "d.terry@datatables.net",
    },
    {
        id: '25',
        SNO: '25',
        FNAME: "Angelica",
        LNAME: "Ramos",
        POSITION: "Chief Executive Officer",
        START: "20017/10/15",
        SALARY: "$6,234,000",
        MAIL: "a.ramos@datatables.net",
    },
    {
        id: '26',
        SNO: '26',
        FNAME: "Connor",
        LNAME: "Johne",
        POSITION: "Web Developer",
        START: "2011/1/25",
        SALARY: "$92,575",
        MAIL: "C.johne@datatables.net",
    },
    {
        id: '27',
        SNO: '27',
        FNAME: "Jennifer",
        LNAME: "Chang",
        POSITION: "Regional Director",
        START: "2012/17/11",
        SALARY: "$546,890",
        MAIL: "j.chang@datatables.net",
    },
    {
        id: '28',
        SNO: '28',
        FNAME: "Brenden",
        LNAME: "Wagner",
        POSITION: "Software Engineer",
        START: "2013/07/14",
        SALARY: "$206,850",
        MAIL: "b.wagner@datatables.net",
    },
    {
        id: '29',
        SNO: '29',
        FNAME: "Fiona",
        LNAME: "Green",
        POSITION: "Chief Operating Officer",
        START: "2015/06/23",
        SALARY: "$345,789",
        MAIL: "f.green@datatables.net",
    },
    {
        id: '30',
        SNO: '30',
        FNAME: "Shou",
        LNAME: "Itou",
        POSITION: "Regional Marketing",
        START: "2013/07/19",
        SALARY: "$335,300",
        MAIL: "s.itou@datatables.net",
    },
    {
        id: '31',
        SNO: '31',
        FNAME: "Michelle",
        LNAME: "House",
        POSITION: "Integration Specialist",
        START: "2016/07/18",
        SALARY: "$76,890",
        MAIL: "m.house@datatables.net",
    },
    {
        id: '32',
        SNO: '32',
        FNAME: "Suki",
        LNAME: "Burks",
        POSITION: "Developer",
        START: "2010/11/45",
        SALARY: "$678,890",
        MAIL: "s.burks@datatables.net",
    },
    {
        id: '33',
        SNO: '33',
        FNAME: "Prescott",
        LNAME: "Bartlett",
        POSITION: "Technical Author",
        START: "2014/12/25",
        SALARY: "$789,100",
        MAIL: "p.bartlett@datatables.net",
    },
    {
        id: '34',
        SNO: '34',
        FNAME: "Gavin",
        LNAME: "Cortez",
        POSITION: "Team Leader",
        START: "2015/1/19",
        SALARY: "$345,890",
        MAIL: "g.cortez@datatables.net",
    },
    {
        id: '35',
        SNO: '35',
        FNAME: "Martena",
        LNAME: "Mccray",
        POSITION: "Post-Sales support",
        START: "2011/03/09",
        SALARY: "$324,050",
        MAIL: "m.mccray@datatables.net",
    },
    {
        id: '36',
        SNO: '36',
        FNAME: "Unity",
        LNAME: "Butler",
        POSITION: "Marketing Designer",
        START: "2014/7/28",
        SALARY: "$34,983",
        MAIL: "u.butler@datatables.net",
    },
    {
        id: '37',
        SNO: '37',
        FNAME: "Howard",
        LNAME: "Hatfield",
        POSITION: "Office Manager",
        START: "2013/8/19",
        SALARY: "$98,000",
        MAIL: "h.hatfield@datatables.net",
    },
    {
        id: '38',
        SNO: '38',
        FNAME: "Hope",
        LNAME: "Fuentes",
        POSITION: "Secretary",
        START: "2015/07/28",
        SALARY: "$78,879",
        MAIL: "h.fuentes@datatables.net",
    },
    {
        id: '39',
        SNO: '39',
        FNAME: "Vivian",
        LNAME: "Harrell",
        POSITION: "Financial Controller",
        START: "2010/02/14",
        SALARY: "$452,500",
        MAIL: "v.harrell@datatables.net",
    },
    {
        id: '40',
        SNO: '40',
        FNAME: "Timothy",
        LNAME: "Mooney",
        POSITION: "Office Manager",
        START: "20016/12/11",
        SALARY: "$136,200",
        MAIL: "t.mooney@datatables.net",
    },
    {
        id: '41',
        SNO: '41',
        FNAME: "Jackson",
        LNAME: "Bradshaw",
        POSITION: "Director",
        START: "2011/09/26",
        SALARY: "$645,750",
        MAIL: "j.bradshaw@datatables.net",
    },
    {
        id: '42',
        SNO: '42',
        FNAME: "Olivia",
        LNAME: "Liang",
        POSITION: "Support Engineer",
        START: "2014/02/03",
        SALARY: "$234,500",
        MAIL: "o.liang@datatables.net",
    },
    {
        id: '43',
        SNO: '43',
        FNAME: "Bruno",
        LNAME: "Nash",
        POSITION: "Software Engineer",
        START: "2015/05/03",
        SALARY: "$163,500",
        MAIL: "b.nash@datatables.net",
    },
    {
        id: '44',
        SNO: '44',
        FNAME: "Sakura",
        LNAME: "Yamamoto",
        POSITION: "Support Engineer",
        START: "2010/08/19",
        SALARY: "$139,575",
        MAIL: "s.yamamoto@datatables.net",
    },
    {
        id: '45',
        SNO: '45',
        FNAME: "Thor",
        LNAME: "Walton",
        POSITION: "Developer",
        START: "2012/08/11",
        SALARY: "$98,540",
        MAIL: "t.walton@datatables.net",
    },
    {
        id: '46',
        SNO: '46',
        FNAME: "Finn",
        LNAME: "Camacho",
        POSITION: "Support Engineer",
        START: "2016/07/07",
        SALARY: "$87,500",
        MAIL: "f.camacho@datatables.net",
    },
    {
        id: '47',
        SNO: '47',
        FNAME: "Serge",
        LNAME: "Baldwin",
        POSITION: "Data Coordinator",
        START: "2017/04/09",
        SALARY: "$138,575",
        MAIL: "s.baldwin@datatables.net",
    },
    {
        id: '48',
        SNO: '48',
        FNAME: "Zenaida",
        LNAME: "Frank",
        POSITION: "Software Engineer",
        START: "2018/01/04",
        SALARY: "$125,250",
        MAIL: "z.frank@datatables.net",
    },
    {
        id: '49',
        SNO: '49',
        FNAME: "Zorita",
        LNAME: "Serrano",
        POSITION: "Software Engineer",
        START: "2017/06/01",
        SALARY: "$115,000",
        MAIL: "z.serrano@datatables.net",
    },
    {
        id: '50',
        SNO: '50',
        FNAME: "Jennifer",
        LNAME: "Acosta",
        POSITION: "Junior Javascript Developer",
        START: "2017/02/01",
        SALARY: "$75,650",
        MAIL: "j.acosta@datatables.net",
    }
];

export const DataTabless = () => {
    const [selectedRows, setSelectedRows] = React.useState([]);
    const [toggleCleared, setToggleCleared] = React.useState(false);
    const [data, setData] = React.useState(tableDataItems);

    const handleRowSelected = React.useCallback((state) => {
        setSelectedRows(state.selectedRows);
    }, []);

    const columns:any = [
        {
            name: "S.NO",
            selector: (row) => [row.SNO],
            sortable: false,
        },
        {
            name: "FIRST NAME",
            selector: (row) => [row.FNAME],
            sortable: true,
        },
        {
            name: "LAST NAME",
            selector: (row) => [row.LNAME],
            sortable: false,
        },
        {
            name: "POSITION",
            selector: (row) => [row.POSITION],
            sortable: true,
        },
        {
            name: "START DATE",
            selector: (row) => [row.START],
            sortable: true,
        },
        {
            name: "SALARY",
            selector: (row) => [row.SALARY],
            sortable: true,
        },
        {
            name: "MAIL",
            selector: (row) => [row.MAIL],
            sortable: false,
        },
    ];
    const contextActions = React.useMemo(() => {
        const handleDelete = (SNO) => {

            setToggleCleared(!toggleCleared);
            setData(differenceBy(data, selectedRows, "SNO"));

        };

        return (
            <Button variant="" className="btn btn-primary mt-2" key="delete" onClick={handleDelete}>
                Delete
            </Button>
        );
    }, [data, selectedRows, toggleCleared]);
    const tableDatas = {
        columns,
        data,
    };
    return (
        <span className="datatable">
            <DataTableExtensions {...tableDatas}>
                <DataTable
                    title
                    columns={columns}
                    data={data}
                    selectableRows
                    contextActions={contextActions}
                    onSelectedRowsChange={handleRowSelected}
                    clearSelectedRows={toggleCleared}
                    pagination
                />
            </DataTableExtensions>
        </span>
    );
};